### ISSUE TITLE
[BUG] Chat bug

### ISSUE THREAD

**Issue by GreeNyTMs** [daffyyyy/CS2-Tags#2]
When i press "Y" for texting into chat, and i dont write anything and i send it, it will send empty message, like

[ADMIN] GreeNyTM:

**Comment by mrdiega** [comment]
I confirm. Some not-so-smart players start taking advantage of this and spamming the chat with empty messages

**Comment by pZyk93** [comment]
Hopefully this will be fixed

**Comment by daffyyyy** [comment]
Try latest build

**Comment by pZyk93** [comment]
> Try latest build

Works great!
