### ISSUE TITLE
Compatible with K4 system

### ISSUE THREAD

**Issue by mrdiega** [daffyyyy/CS2-Tags#4]
tags build 21, css 84
In my config only nick color is indicated, but at the same time, half of the players on scoreboard dont display a rank from K4.

`tags.json`
```
{
  "tags": {
    "everyone": {
      "prefix": "",
      "nick_color": "{LightBlue}",
      "message_color": "",
      "scoreboard": ""
    },
    "76561198039521496": {
      "prefix": "",
      "nick_color": "{DarkBlue}",
      "message_color": "",
      "scoreboard": ""
    }
  }
}
```
![20231130134557_1](https://github.com/daffyyyy/CS2-Tags/assets/79888956/cbd5c1de-cc38-4e07-9375-3476b4609239)

**Comment by daffyyyy** [comment]
Try latest version
